//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srRndcEnvioUnitario.IBPMServices")]
    public interface IBPMServices {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:BPMServicesIntf-IBPMServices) del mensaje AtenderMensajeRNDCRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:BPMServicesIntf-IBPMServices#AtenderMensajeRNDC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCResponse AtenderMensajeRNDC(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BPMServicesIntf-IBPMServices#AtenderMensajeRNDC", ReplyAction="*")]
        System.Threading.Tasks.Task<Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCResponse> AtenderMensajeRNDCAsync(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:BPMServicesIntf-IBPMServices) del mensaje AtenderMensajeBPMRequest no coincide con el valor predeterminado (http://tempuri.org/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:BPMServicesIntf-IBPMServices#AtenderMensajeBPM", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMResponse AtenderMensajeBPM(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:BPMServicesIntf-IBPMServices#AtenderMensajeBPM", ReplyAction="*")]
        System.Threading.Tasks.Task<Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMResponse> AtenderMensajeBPMAsync(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeRNDC", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeRNDCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Request;
        
        public AtenderMensajeRNDCRequest() {
        }
        
        public AtenderMensajeRNDCRequest(string Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeRNDCResponse", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeRNDCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AtenderMensajeRNDCResponse() {
        }
        
        public AtenderMensajeRNDCResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeBPM", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeBPMRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Request;
        
        public AtenderMensajeBPMRequest() {
        }
        
        public AtenderMensajeBPMRequest(string Request) {
            this.Request = Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AtenderMensajeBPMResponse", WrapperNamespace="urn:BPMServicesIntf-IBPMServices", IsWrapped=true)]
    public partial class AtenderMensajeBPMResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string @return;
        
        public AtenderMensajeBPMResponse() {
        }
        
        public AtenderMensajeBPMResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBPMServicesChannel : Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BPMServicesClient : System.ServiceModel.ClientBase<Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices>, Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices {
        
        public BPMServicesClient() {
        }
        
        public BPMServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BPMServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPMServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BPMServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCResponse Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices.AtenderMensajeRNDC(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest request) {
            return base.Channel.AtenderMensajeRNDC(request);
        }
        
        public string AtenderMensajeRNDC(string Request) {
            Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest inValue = new Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest();
            inValue.Request = Request;
            Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCResponse retVal = ((Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices)(this)).AtenderMensajeRNDC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCResponse> Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices.AtenderMensajeRNDCAsync(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest request) {
            return base.Channel.AtenderMensajeRNDCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCResponse> AtenderMensajeRNDCAsync(string Request) {
            Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest inValue = new Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeRNDCRequest();
            inValue.Request = Request;
            return ((Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices)(this)).AtenderMensajeRNDCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMResponse Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices.AtenderMensajeBPM(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest request) {
            return base.Channel.AtenderMensajeBPM(request);
        }
        
        public string AtenderMensajeBPM(string Request) {
            Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest inValue = new Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest();
            inValue.Request = Request;
            Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMResponse retVal = ((Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices)(this)).AtenderMensajeBPM(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMResponse> Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices.AtenderMensajeBPMAsync(Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest request) {
            return base.Channel.AtenderMensajeBPMAsync(request);
        }
        
        public System.Threading.Tasks.Task<Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMResponse> AtenderMensajeBPMAsync(string Request) {
            Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest inValue = new Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.AtenderMensajeBPMRequest();
            inValue.Request = Request;
            return ((Transer.Tecnologia.Automatizacion.EnvioUnitarioVs1.srRndcEnvioUnitario.IBPMServices)(this)).AtenderMensajeBPMAsync(inValue);
        }
    }
}
